/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyectgodoc.VistaApp;

import com.itextpdf.text.Element;
import com.mycompany.proyectgodoc.Dao.FormularioDao;
import com.mycompany.proyectgodoc.Modelo.Contratista;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import com.itextpdf.text.Document;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;

/**
 *
 * @author USUARIO
 */
public class Formulario extends javax.swing.JFrame {
    
   

    
    public Formulario() {
        initComponents();
        
        //codigo para ubicar formulario en el centro de la pantalla
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textDocumento1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textLugarEX = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textValorC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jDateFechaIn = new com.toedter.calendar.JDateChooser();
        jDateFechaFin = new com.toedter.calendar.JDateChooser();
        jLfechaCon = new javax.swing.JLabel();
        jDateFechaCon = new com.toedter.calendar.JDateChooser();
        jBGenerar = new javax.swing.JButton();
        jBVolver = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  DATOS DEL CONTRATISTA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 270, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        textNombre.setBackground(new java.awt.Color(255, 255, 255));
        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombres");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellidos");

        textApellido.setBackground(new java.awt.Color(255, 255, 255));
        textApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textApellidoActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Dirreción");

        textDireccion.setBackground(new java.awt.Color(255, 255, 255));
        textDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDireccionActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Documento ");

        textDocumento1.setBackground(new java.awt.Color(255, 255, 255));
        textDocumento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDocumento1ActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Lugar de expedición");

        textLugarEX.setBackground(new java.awt.Color(255, 255, 255));
        textLugarEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLugarEXActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(textDocumento1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textLugarEX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addContainerGap(73, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textDocumento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textLugarEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 280, 320));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Fecha de Iniciación");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Valor contrato");

        textValorC.setBackground(new java.awt.Color(255, 255, 255));
        textValorC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textValorCActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Fecha de finalización");

        jLfechaCon.setForeground(new java.awt.Color(0, 0, 0));
        jLfechaCon.setText("Fecha Contrato");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel17)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLfechaCon)
                    .addComponent(jLabel7)
                    .addComponent(textValorC, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jDateFechaCon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateFechaFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(jDateFechaIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textValorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateFechaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLfechaCon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateFechaCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel17))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 280, 320));

        jBGenerar.setBackground(new java.awt.Color(255, 255, 255));
        jBGenerar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBGenerar.setForeground(new java.awt.Color(0, 0, 0));
        jBGenerar.setText("GENERAR");
        jBGenerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGenerarActionPerformed(evt);
            }
        });
        jPanel1.add(jBGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 95, 33));

        jBVolver.setBackground(new java.awt.Color(204, 204, 204));
        jBVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBVolver.setForeground(new java.awt.Color(0, 0, 0));
        jBVolver.setText("Volver");
        jBVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });
        jPanel1.add(jBVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 88, 33));

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));
        jPanel4.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreActionPerformed

    private void textApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textApellidoActionPerformed

    private void textDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDireccionActionPerformed

    private void textDocumento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDocumento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDocumento1ActionPerformed

    private void textLugarEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLugarEXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLugarEXActionPerformed

    private void textValorCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textValorCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textValorCActionPerformed

    private void jBGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGenerarActionPerformed
        // TODO add your handling code here:
        String fechaInicio = ((JTextField) jDateFechaIn.getDateEditor().getUiComponent()).getText();
        String fechaFin = ((JTextField) jDateFechaFin.getDateEditor().getUiComponent()).getText();
        String fechaCon = ((JTextField) jDateFechaCon.getDateEditor().getUiComponent()).getText();
        if (textApellido.getText().equals("") || textNombre.getText().equals("") || textDocumento1.getText().equals("") || textDireccion.getText().equals("") || textLugarEX.getText().equals("") || textValorC.getText().equals("") || fechaInicio.equals("") || fechaFin.equals("") || fechaCon.equals("")) {
            JOptionPane.showMessageDialog(null, "Hay Campos Vacios, por favor verifique sus datos");
        } else {
            FormularioDao formularioDao = new FormularioDao();
            Contratista contratista = new Contratista();
            // seteamos los variables
            contratista.setNombre(textNombre.getText());
            contratista.setApellido(textApellido.getText());
            contratista.setCedula(textDocumento1.getText());
            contratista.setDireccion(textDireccion.getText());
            contratista.setLugarExpedicion(textLugarEX.getText());
            contratista.setValorContrato(textValorC.getText());
            contratista.setFechaInicio(fechaInicio);
            contratista.setFechaFin(fechaFin);
            contratista.setFechaContrato(fechaCon);
            
            

            if (formularioDao.guardar(contratista)) {
                JOptionPane.showMessageDialog(null, "Guardado");

            } else {

                JOptionPane.showMessageDialog(null, "Error al guardar");
                

            }
        }
        
        String nombre = textApellido.getText();
        String apellido = textNombre.getText();
        String documento = textDocumento1.getText();
        String valorC = textValorC.getText();

        try {
            
            Document doc = new Document();
            
            FileOutputStream file = new FileOutputStream(nombre + " ContratoNoColombiano.pdf");
            PdfWriter.getInstance(doc, file);
            
            doc.setMargins(68.03f, 68.03f, 72f, 72f);
            doc.open();
            
            Image imagen = Image.getInstance("D:\\Users\\USUARIO\\Documents\\NetBeansProjects\\PROYECTGODOC\\Imagenes\\enca.png");
            imagen.scaleAbsoluteWidth(200);
            imagen.scaleAbsoluteHeight(130);
            imagen.scaleAbsolute(460, 100);
            doc.add(imagen);
            
            
            Paragraph texto1 = new Paragraph("Entre los suscritos: CARMEN CECILIA QUERO DE GONZALEZ, mayor de edad vecino de esta ciudad,  "
                    + "portadora de la cedula de ciudadanía 37.219.308 expedida en Cúcuta, en su condición de REPRESENTANTE LEGAL "
                    + "DE LA FUNDACION DE ESTUDIOS SUPERIORES COMFANORTE FESC, entidad sin Ánimo de Lucro, con Personería Jurídica"
                    + " Resolución No. 4172 del 25 de agosto de 1993, quien en adelante se denominara EL CONTRATANTE, por una parte,"
                    + " y, " + nombre + " " + apellido +" también mayor de edad, portador(a) del documento de identidad C.E. No. " + documento +", persona natural no "
                    + "residente en el territorio colombiano, quien para efectos del presente documento se denominara CONTRATISTA,"
                    + " por la otra parte, hemos convenido celebrar el presente CONTRATO DE PRESTACION DE SERVICIOS PROFESIONALES con"
                    + " base a las siguientes consideraciones:");
            texto1.setAlignment(Element.ALIGN_JUSTIFIED);
            doc.add(texto1);
            doc.add(new Paragraph("\n"));
            BaseFont fuente = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.CP1250, true);
            Paragraph texto2 = new Paragraph("La FUNDACION DE ESTUDIOS SUPERIORES COMFANORTE FESC, requiere el apoyo de personal calificado para la "
                    + "ejecución y desarrollo de diferentes programas académicos de la FESC, para lo cual el presente contrato de prestación de servicios"
                    + " se desarrollará conforme a las siguientes clausulas:" + "\n" + "\n"
                    
                    + "CLAUSULA PRIMERA: OBJETO. El contratista prestara sus servicios "
                    + "profesionales como apoyo a la ejecución de los diferentes proyectos académicos de la FESC,  orientando al talento humano adscrito a "
                    + "las diferentes actividades misionales y administrativas,  mediante asesorías, consultorías y desarrollo académico adicional, garantizando "
                    + "el crecimiento y mejora en relación con los conocimientos, actitudes hacia el trabajo,  y calidad humana del recurso para el cual se"
                    + " contrata en el tiempo acordado entre las partes." + "\n" + "\n" 
                    
                    + "CLAUSULA SEGUNDA: VALOR. El valor del presente contrato es de $" + valorC + " , monto que está sujeto a la programación final de las acciones concertadas. "
                    + "La programación se realiza de acuerdo con la disponibilidad del tiempo que previamente mediante el formato establecido FPESF-4.1-5, EL CONTRATISTA "
                    + "informa al CONTRATANTE y es el soporte para la ejecución de las actividades adscritas al presente contrato." + "\n" + "\n" +"\n" );
            texto2.setAlignment(Element.ALIGN_JUSTIFIED);
            doc.add(texto2);
                    
            doc.add(new Paragraph("\n"));
            Image imagen2 = Image.getInstance("D:\\Users\\USUARIO\\Documents\\NetBeansProjects\\PROYECTGODOC\\Imagenes\\enca.png");
            imagen2.scaleAbsoluteWidth(200);
            imagen2.scaleAbsoluteHeight(130);
            imagen2.scaleAbsolute(460, 100);
            doc.add(imagen2);
            Paragraph texto3 = new Paragraph ("CLAUSULA TERCERA: FORMA DE PAGO. El presente contrato se cancelará previa presentación de la cuenta de cobro, cuyo valor estará soportado en la"
                    + " programación final de las acciones concertadas. Asimismo se deberá anexar el informe de actividades firmado por el supervisor del contrato y póliza"
                    + " o seguro de viaje. " + "\n" + "\n" 
                    
                    + "PARAGRAFO PRIMERO: LA FESC podrá retener las sumas correspondientes a los impuestos en los porcentajes establecidos en la ley, así mismo La FESC queda"
                    + " exonerada de pagar al CONTRATISTA el valor que corresponda a las actividades planeadas no ejecutadas. " + "\n" + "\n" 
                    
                    + "PARAGRAFO SEGUNDO: LA FESC no se responsabilizará por la demora presentada en el pago al CONTRATISTA cuando ella fuere ocasionada por encontrarse incompleta"
                    + " la documentación de soporte o no se ajuste a cualquiera de las condiciones establecidas en el presente contrato. " + "\n" + "\n" 
                    
                    + "PARAGRAFO TERCERO: LA FESC no cancelará las sumas que excedan el valor total establecido en el presente contrato o no estén estipuladas dentro del objeto de "
                    + "la misma, a excepción de las autorizaciones otorgadas previamente por el ordenador del gasto." + "\n" + "\n" 
                    
                    + "CLAUSULA CUARTA: PLAZO El contratista desarrollara las actividades contratadas en un plazo desde el " + fechaInicio + " hasta el " + fechaFin + ", previo cumplimiento de los "
                    + "requisitos de perfeccionamiento del contrato." + "\n" + "\n" 
                    
                    + "CLAUSULA QUINTA: SUPERVISIÓN. a) La supervisión del desarrollo del objeto del presente contrato de prestación de servicios profesionales será realizada por el "
                    + "director del programa b) Gestión humana verificará el cumplimiento mediante la revisión de los parámetros establecidos. " + "\n" + "\n" + "\n" + "\n");
            texto3.setAlignment(Element.ALIGN_JUSTIFIED);
            doc.add(texto3);
   
            Image imagen3 = Image.getInstance("D:\\Users\\USUARIO\\Documents\\NetBeansProjects\\PROYECTGODOC\\Imagenes\\enca.png");
            imagen3.scaleAbsoluteWidth(200);
            imagen3.scaleAbsoluteHeight(130);
            imagen3.scaleAbsolute(460, 100);
            doc.add(imagen3);
            
            Paragraph texto4 = new Paragraph("\n"+ "CLAUSULA SEXTA: OBLIGACIONES DEL CONTRATISTA: a) Abstenerse de tener relaciones personales con los individuos que integran la comunidad estudiantil , dentro y "
                    + "fuera de la institución durante el termino del presente contrato b) Cumplir el Estatuto y  los Reglamentos de la FESC que le apliquen para garantizar el cumplimiento "
                    + "del contrato c) Dará buen uso a los materiales devolutivos y de consumo según las directrices de la FESC y devolverá los mismos al finalizar el contrato d) Cumplir en "
                    + "forma eficiente en el plazo establecido los trabajos encomendados y aquellas obligaciones que se generen de acuerdo con la naturaleza del servicio. e)  Se obliga a cumplir"
                    + " con lo estipulado en las demás cláusulas y condiciones previstas en este documento. D) A permitir el tratamiento de los datos personales que se suministren en desarrollo "
                    + "del presente objeto, durante todo el tiempo de permanencia en la entidad y después de terminada la relación siempre y cuando exista un deber de conservación legal o contractual"
                    + " por parte de La FESC. La autorización de tratamiento de datos personales se otorga por parte del docente dentro de lo descrito en la Política de Protección de Datos Personales, "
                    + "que es conocida por el docente, en todos los casos el docente podrá hacer uso de sus derechos de Habeas Data (conocer, actualizar y rectificar su información con excepción a lo"
                    + " establecido por ley en la siguiente dirección: Av 4 #15-14 barrio La Playa en Cúcuta, o en la sede Ocaña en la dirección KDX 194-785 barrio Llano de los Alcaldes, vía universitaria; "
                    + "a través de correo electrónico habeasdata@fesc.edu.co, o al teléfono (037) 582 9292 Ext: 118. " + "\n" + "\n" 
            
                    + "CLAUSULA SEPTIMA: OBLIGACIONES DE LA FESC: a) Facilitar el acceso a la información y elementos que sean necesarios, de manera oportuna, para la debida ejecución del objeto del contrato, "
                    + "b) La FESC cancelara al CONTRATISTA la cuenta de cobro acorde con las políticas establecidas por la institución c) LA FESC se obliga a cumplir con lo estipulado en las demás cláusulas y "
                    + "condiciones previstas en este documento. " + "\n" + "\n" + "\n" + "\n" 
                    );
            texto4.setAlignment(Element.ALIGN_JUSTIFIED);
            doc.add(texto4);
            doc.add(new Paragraph("\n"));
            
            Image imagen4 = Image.getInstance("D:\\Users\\USUARIO\\Documents\\NetBeansProjects\\PROYECTGODOC\\Imagenes\\enca.png");
            imagen4.scaleAbsoluteWidth(200);
            imagen4.scaleAbsoluteHeight(130);
            imagen4.scaleAbsolute(460, 100);
            doc.add(imagen4);
            
            Paragraph texto5 = new Paragraph("\n"+ "CLAUSULA OCTAVA: PROHIBICION DE CEDER: El CONTRATISTA no podrá ceder total o parcialmente el presente Contrato de prestación de servicios profesionales a persona alguna "
                    + "sea natural o jurídica, ni hacerse sustituir por terceros en el ejercicio de los derechos o en el cumplimiento de las obligaciones que en el mismo constan, sin el consentimiento previo, expreso "
                    + "y escrito de la FESC." + "\n" + "\n"
                    
                    + "CLAUSULA NOVENA: CLÁUSULA DE CONFIDENCIALIDAD. La información confidencial y todos los derechos derivadas de la misma, permanecerán como propiedad de la FUNDACIÓN DE ESTUDIOS SUPERIORES COMFANORTE, "
                    + "conforme a las obligaciones contenidas en el documento denominado “ANEXO A LA CLAUSULA NOVENA DEL CONTRATO DE PRESTACION DE SERVICIOS PROFESIONALES”, el cual ha sido firmado por las partes y hace parte "
                    + "integral del presente contrato individual de trabajo. " + "\n" + "\n"
                    
                    + "El incumplimiento de esta cláusula por parte del TRABAJADOR, una vez detectado y demostrado el hecho, será considerada como una falta grave y puede suponer el despido disciplinario, es decir, sin indemnización, "
                    + "en aquellos casos especialmente flagrantes. Por otro lado, en el supuesto de que la revelación de la información protegida por la cláusula de confidencialidad se produjese una vez acabada la presente relación laboral, "
                    + "la FUNDACIÓN DE ESTUDIOS SUPERIORES COMFANORTE estará en su derecho de entablar las acciones legales que considere pertinentes." + "\n" + "\n"
                    
                    + "CLAUSULA DECIMA: RESPONSABILIDAD DEL CONTRATISTA: El contratista responderá civil y penalmente por sus acciones y omisiones, en la actuación del presente Contrato. En los términos de la Ley y como consecuencia de ellos "
                    + "quedará sujeto a las sanciones establecidas en la misma." + "\n" + "\n" + "\n");
            texto5.setAlignment(Element.ALIGN_JUSTIFIED);
            doc.add(texto5);
            
            Image imagen5 = Image.getInstance("D:\\Users\\USUARIO\\Documents\\NetBeansProjects\\PROYECTGODOC\\Imagenes\\enca.png");
            imagen5.scaleAbsoluteWidth(200);
            imagen5.scaleAbsoluteHeight(130);
            imagen5.scaleAbsolute(460, 100);
            doc.add(imagen5);
            
            doc.add(new Paragraph("\n"));
                    
            Paragraph texto6 = new Paragraph("CLAUSULA DECIMA PRIMERA: TRATAMIENTO DE DATOS PERSONALES Permitir el tratamiento de sus datos personales, de conformidad a las políticas de protección de datos establecidas por la institución y la normatividad vigente." + "\n" + "\n"
                    
                    + "CLAUSULA DECIMA SEGUNDA: TERMINACIÓN DEL CONTRATO. El presente contrato terminará por vencimiento del plazo pactado. También podrá darse por terminado por mutuo acuerdo entre las partes, o en forma unilateral por LA FESC por el "
                    + "incumplimiento de las obligaciones a cargo del CONTRATISTA derivados del contrato y no dará lugar al pago de ningún tipo de indemnización a favor del CONTRATISTA. " + "\n" + "\n"
                    
                    + "CLAUSULA DECIMA TERCERA: INDEPENDENCIA EL CONTRATISTA prestará sus servicios en forma independiente y con total autonomía técnica, administrativa y financiera. En ningún caso existirá relación laboral entre LA FESC y EL CONTRATISTA, "
                    + "en consecuencia, EL CONTRATISTA asume en forma total y exclusiva la absoluta responsabilidad que se derive de sus actos u omisiones, así como por la calidad e idoneidad de los servicios que preste. " + "\n" + "\n"
                    
                    + "CLAUSULA DECIMA CUARTA: INFORME DE ENTREGA A LA TERMINACIÓN DEL CONTRATO – Conforme lo señala el acuerdo de confidencialidad, es obligación del CONTRATISTA informar inmediatamente a la terminación definitiva de su contrato, bases de "
                    + "datos, equipos, información técnica, académica, que utilizó para poder ejecutar el objeto del contrato, para lo cual deberá diligenciar el formato denominado “INFORME ENTREGA POR FINALIZACIÓN DE CONTRATO DE PRESTACIÓN DE SERVICIOS” "
                    + "implementado por la FESC. Aunado a lo anterior, EL CONTRATISTA se compromete a tramitar y obtener el respectivo paz y salvo ante las dependencias de la institución, para lo cual, el CONTRATISTA acepta expresamente desde ahora, que la "
                    + "omisión, inobservancia e incumplimiento a lo dispuesto en esta cláusula conlleva a la retención de sus honorarios y la consecuente consignación de estos valores a expensas de una autoridad judicial para que, a luz del proceso jurídico "
                    + "pertinente se compensen los daños materiales e inmateriales que esta omisión le genere a La FESC." + "\n" + "\n");
            
            texto6.setAlignment(Element.ALIGN_JUSTIFIED);
            doc.add(texto6);
            Image imagen6 = Image.getInstance("D:\\Users\\USUARIO\\Documents\\NetBeansProjects\\PROYECTGODOC\\Imagenes\\enca.png");
            imagen6.scaleAbsoluteWidth(200);
            imagen6.scaleAbsoluteHeight(130);
            imagen6.scaleAbsolute(460, 100);
            doc.add(imagen6);
            
            doc.add(new Paragraph("\n"));
                    
            Paragraph texto7 = new Paragraph("CLAUSULA DECIMA QUINTA: PROPIEDAD INTELECTUAL. – Si de la ejecución del presente contrato resultan estudios, investigaciones, descubrimientos, invenciones, información, mejoras y/o diseños, éstos pertenecen a la FESC, sin perjuicio del "
                    + "respeto al derecho moral consagrado en la Ley. Así mismo, EL CONTRATISTA garantiza que los trabajos y servicios prestados a la FESC por el objeto de este contrato no infringen ni vulneran los derechos de propiedad " + "\n" + "\n"
                    
                    + "intelectual o industrial o cualesquiera otros derechos legales o contractuales de terceros. Las invenciones – proyectos y demás se regirán por la normatividad establecida a nivel nacional por el Órgano Legislativo responsable y lo consignado "
                    + "en el Reglamento de Derechos de Propiedad Intelectual establecido por la FESC y aprobado por el órgano de gobierno competente" + "\n" + "\n"
                    
                    + "CLAUSULA DECIMA QUINTA: NO EXCLUSIVIDAD. Las partes de común acuerdo establecen que no existirá ningún vínculo de exclusividad en el desarrollo del presente Contrato, por lo tanto, el CONTRATISTA podrá suscribir otros contratos con características "
                    + "similares, sin que ello pueda alegarse como incumplimiento del presente contrato, respetando los tiempos concertados para la ejecución del presente." + "\n" + "\n"
                    
                    + "En constancia se firma el presente contrato en San José de Cúcuta, el día" + fechaCon /*fecha contrato*/ + "\n" + "\n" + "\n" + "\n" +"\n"
                    
                    + "CONTRATANTE                                                           CONTRATISTA" + "\n"
                    + "FESC                                                                  "+ nombre + "\n"
                    + "NIT. 800.235.151-5                                                      C.C "
                    
            
            
            );
            texto7.setAlignment(Element.ALIGN_JUSTIFIED);
            doc.add(texto7);
            
            doc.close();
            JOptionPane.showMessageDialog(null, "CONTRATO CREADO");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR AL CREAR CONTRATO");
        }
        

    }//GEN-LAST:event_jBGenerarActionPerformed

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        // TODO add your handling code here:
        
        VistaMenu Vmenu = new VistaMenu();
        Vmenu.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jBVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBGenerar;
    public javax.swing.JButton jBVolver;
    public com.toedter.calendar.JDateChooser jDateFechaCon;
    public com.toedter.calendar.JDateChooser jDateFechaFin;
    public com.toedter.calendar.JDateChooser jDateFechaIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLfechaCon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JTextField textApellido;
    public javax.swing.JTextField textDireccion;
    public javax.swing.JTextField textDocumento1;
    public javax.swing.JTextField textLugarEX;
    public javax.swing.JTextField textNombre;
    public javax.swing.JTextField textValorC;
    // End of variables declaration//GEN-END:variables
}
